[server]
headless = true
enableCORS = false
enableStaticServing = true
# Mantener conexión viva en móvil / Tailscale
websocketPingInterval = 20
websocketPingTimeout = 120

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[runner]
fastReruns = true
